# Generated by Django 4.0 on 2024-12-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='numGen',
            field=models.CharField(default=1, max_length=10, primary_key=False, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personas',
            name='id',
            field=models.CharField(primary_key=True, max_length=2),
        ),
    ]
