# Generated by Django 4.0 on 2025-01-13 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personas',
            table=None,
        ),
    ]
