# Generated by Django 4.0 on 2024-12-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_personas_numgen_alter_personas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='numGen',
            field=models.IntegerField(max_length=10, primary_key=False, serialize=False),
        ),
    ]
