# Generated by Django 4.0 on 2024-12-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0003_alter_personas_numgen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='numGen',
        ),
        migrations.AlterField(
            model_name='personas',
            name='id',
            field=models.AutoField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
