# Generated by Django 4.0 on 2024-12-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0005_alter_personas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
