# Generated by Django 4.0 on 2024-12-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0006_alter_personas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='id',
            field=models.AutoField(primary_key=True, auto_created=True),
        ),
    ]
