# Generated by Django 4.0 on 2024-12-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0007_alter_personas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
