# Generated by Django 4.0 on 2024-12-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0008_alter_personas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='edad',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personas',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
