# Generated by Django 4.0 on 2024-12-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0009_personas_edad_personas_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
