# Generated by Django 4.0 on 2024-12-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0010_alter_personas_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especie', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('mantenedor', models.CharField(max_length=100)),
            ],
        ),
    ]
