# Generated by Django 4.0 on 2024-12-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0011_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('consola', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
