# Generated by Django 4.0 on 2024-12-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0012_videojuego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='disponibilidad',
            field=models.CharField(choices=[('tienda', 'Disponible en Tienda'), ('envio', 'Solo Envío'), ('ambos', 'Tienda y Envío')], default='ambos', max_length=10),
        ),
    ]
