# Generated by Django 4.0 on 2024-12-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0013_remove_videojuego_descripcion_videojuego_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
