# Generated by Django 4.0 on 2024-12-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0014_alter_videojuego_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='mantenedor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='disponibilidad',
            field=models.CharField(choices=[('tienda', 'Disponible en Tienda'), ('envio', 'Solo Envío'), ('ambos', 'Tienda y Envío'), ('sin_stock', 'Sin Stock')], default='ambos', max_length=10),
        ),
    ]
