# Generated by Django 4.0 on 2024-12-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0015_animal_nombre_alter_animal_especie_alter_animal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='disponibilidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
