# Generated by Django 4.0 on 2025-01-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0016_alter_videojuego_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaImportada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
